# Slowly changing it to match our project specs
# Stages - lint, build, deploy
# Lint - re-installs npm dependencies and runs lint
# unit test stage - commented out for now
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/development/cicd/templates/
# This specific (default) template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - lint
  - build
  - deploy

lint:          # lint stage
  stage: lint
  image: node:18
  script:
    - cd server
    - npm install
    - npm run lint
    - cd ../client
    - npm install
    - npm run lint

build-job:       # This job runs in the build stage, which runs first.
  stage: build.  # only runs if lint passes
  image: node:18
  script:
    - cd client
    - npm install
    - npm run build

deploy:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  before_script:
    - apk add --no-cache openssh-client git
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
  script:
#     - echo "test"
    - ssh "$SERVER_USER@$SERVER_IP" "
        cd /var/www/zoar &&
        git pull origin main &&
        cd server &&
        npm install &&
        cd ../client &&
        npm install &&
        npm run build &&
        pm2 restart all
      "
  only:
    - main
